### ISSUE TITLE
Microsoft Teams & Outlook blank screens

### ISSUE THREAD

**Issue by jstrupek** [getstation/desktop-app#150] opened 2023-05-16 16:33 UTC
Downloaded latest version on Windows x64. After logging into Microsoft greeted with a blank screen on both Outlook and Teams. Not sure if this is a permissions thing on Microsoft admin-side? Not sure what to add to make it work here.

![2023-05-16 11_32_13-Station](https://github.com/getstation/desktop-app/assets/119471218/0d48d02f-8cfa-4559-b9a2-1e4c3e6e70c6)

**Comment by xalt7x** [comment] 2023-05-17 15:49
Duplicate of #143

**Comment by viktor44** [comment] 2023-05-17 16:10
#80

**Closed by viktor44** 2023-05-17 16:10 UTC
Labels: duplicate
