### ISSUE TITLE
QR code for WhatsApp does not generate

### ISSUE THREAD

**Issue by alexbotev** [getstation/desktop-app#3] opened 2021-07-14 13:58 UTC
I wanted to pair the Station with WhatsApp but I cannot get the QR code, there is this circle moving. I restarted the Station, reset the app (WhatsApp), reloaded, did not help
![wa](https://user-images.githubusercontent.com/14941931/125634490-326fcb22-ce06-40ae-b10c-ffa2c4d5d4ba.png)

I have macOS 11.5 (the latest public beta)

**Comment by sven-ahrens** [comment] 2021-07-14 14:06
Not only WhatsApp but Telegram too. I can reproduce this problem

<img width="740" alt="Bildschirmfoto 2021-07-14 um 16 06 10" src="https://user-images.githubusercontent.com/18313443/125635965-b3498fd3-ba57-45af-9a94-b3a09d99924e.png">

**Comment by onkelandy** [comment] 2021-07-14 14:36
Same here using Mac OS 10.15.7 Catalina

**Comment by jescalan** [comment] 2021-07-14 16:07
This one is really tragic. I was hoping it would at least work out of the box...

**Comment by alexbotev** [comment] 2021-07-14 16:46
> This one is really tragic. I was hoping it would at least work out of the box...

I am taking it as a beta version, I hope somebody will fix it after the company went wrong last September and bankrupted (my guess from today's e-mail).

**Comment by cobold0815** [comment] 2021-07-14 21:03
> Not only WhatsApp but Telegram too. I can reproduce this problem
> 
> <img alt="Bildschirmfoto 2021-07-14 um 16 06 10" width="740" src="https://user-images.githubusercontent.com/18313443/125635965-b3498fd3-ba57-45af-9a94-b3a09d99924e.png">
> 
> **EDIT**: I'm on macOS Big Sur 11.4 and installed Station v2.0.9

Same setup here and also the same problem.

**Comment by sven-ahrens** [comment] 2021-07-15 06:48
This issue here is related to https://github.com/getstation/desktop-app/issues/9

Most issues that have been filed yesterday kinda depend on this Electron upgrade. I tried to either add Telegram or WhatsApp by myself or even Gmail as you can see in that issue here: https://github.com/getstation/desktop-app/issues/2 but they all won't work because the Google Chrome Version used in the current Electron version is outdated.

So if I try to add WhatsApp by myself, WhatsApp will tell me (and others too), that Google Chrome is outdated and that I need to update it.

As @magne4000 described this as rather difficult to add, who knows when there will be a fix for this issue here

**Comment by jescalan** [comment] 2021-07-15 15:49
I think what baffles me most is that in the closed-source version of station, this worked fine. So I believe that the issue is complex, but also they clearly already have fixed it, and given that I am confused by why it regressed or how it would be difficult to apply a fix that has already been made on the same software 🤔 

I'm sure there's something going on that I just dont understand here, but it's also disappointing to hear that the software will be open sourced, and then a version that doesn't really work at all is open sourced with a "complex issue" in it that nobody knows when will be fixed.

**Comment by thuehn** [comment] 2021-07-20 20:40
hi all,

Do we have a workaround for the time needed to get the current open source release fixed ?
Where can I download the latest proprietary version of station ? ... my google search did not point me to some reasonable station.dmg.

Greetings Thomas

**Comment by realrill** [comment] 2021-07-26 10:21
Any update on this?

Looks like a major issue that affects many people/service and makes the app not much useful.

**Comment by SnShine** [comment] 2021-07-27 06:18
Yep. Discord qr, telegram, whatsapp qr all not loading. At least in discord we can login with mail, pass. But for telegram and whatsapp we can't even login as qr is not loaded.

I've looked at Franz, Ferdi and Rambox and this looks more polished than all of them. Can anyone suggest better alternatives for mac?

**Comment by DickonForKing** [comment] 2021-07-29 06:40
I'm having the same issue, hope this can get fixed soon.

**Comment by Joshstomp** [comment] 2021-08-05 18:13
I have this issue too.

**Comment by shayaknyc** [comment] 2021-08-05 21:27
> I think what baffles me most is that in the closed-source version of station, this worked fine. So I believe that the issue is complex, but also they clearly already have fixed it, and given that I am confused by why it regressed or how it would be difficult to apply a fix that has already been made on the same software 🤔
> 
> I'm sure there's something going on that I just dont understand here, but it's also disappointing to hear that the software will be open sourced, and then a version that doesn't really work at all is open sourced with a "complex issue" in it that nobody knows when will be fixed.

Here's an open-source aggregator for all your chat/comms platforms - but none of them work. Yeah, great..... I was using Franz for a while, but I a) loathe having to make yet ANOTHER user account for no appreciable reason other than for tracking purposes which is not a good enough reason, and b) limited to 3 services on the free version WITH a random 15-second ad which forces you to keep the window in the foreground until the countdown ends so you can clear the ad and get access to your chats. This is a whole wide mess, and I agree with you @jescalan while it may be complicated, when the platforms they're supposed to support DON'T WORK, then where's the utility in a project like Station?

**Comment by joost** [comment] 2021-08-16 10:12
Same as @SnShine .. Station is looking nice. But without being able to login to services it not very useful :)
Any good alternative for Mac?

**Comment by realrill** [comment] 2021-08-18 07:24
Unsure if anyone is aware of this: https://medium.com/@julien_26779/handing-station-to-mankind-b1225e4e7413

With all my optimism, I doubt this bug will be fixed then. Sorry to see such a great app becomes history soon.

I changed back to Rambox. It doesn't have that nice UI as Station has, but it works.

**Comment by sven-ahrens** [comment] 2021-08-18 07:36
> Unsure if anyone is aware of this: https://medium.com/@julien_26779/handing-station-to-mankind-b1225e4e7413
> 
> With all my optimism, I doubt this bug will be fixed then. Sorry to see such a great app becomes history soon.
> 
> I changed back to Rambox. It doesn't have that nice UI as Station has, but it works.

You can have a look at https://stackbrowser.com/

**Comment by onkelandy** [comment] 2021-08-18 07:53
This is also a good alternative with very similar UI: https://getferdi.com/download/

**Comment by paulipotter** [comment] 2021-09-16 15:06
I'm still having the same issue. I'm on macOS 11.5.2

**Comment by realrill** [comment] 2021-09-16 17:30
> Unsure if anyone is aware of this: https://medium.com/@julien_26779/handing-station-to-mankind-b1225e4e7413

Guys, the fact is that the original creators left the Community version behind and they handed over to the mankind. Pretty pointless adding any more comment about the sad reality that doesn't work. They won't fix it regardless how much we moan about it. :/

Either we all move to an active alternative or anyone feel free to make the change as a PR. That hopefully gets merged.
I know nothing about JS so I can't do anything. I'm following this thread simple because waiting for a notification about a new PR that makes it closed :)

**Comment by PietroSferrino** [comment] 2021-09-19 15:36
Well. Nice to know. Thank You.
Now we know we can DEFINITELY change provider.

Il Gio 16 Set 2021, 20:31 realrill ***@***.***> ha scritto:

**Comment by ikellenberger** [comment] 2021-10-01 05:37
Root cause might be that Chrome used within Station is outdated, see e.g. https://www.ecosia.org/search?q=whatsapp+qr+code+not+loading
Station 2.0.9 seems to use Chrome 78.0, which dates back to 2019-10. See 'Help' > 'About Station'. Current version of Chrome would be 94.0, as of 2021-10.
So my guess is that Chrome has to be updated...

**Comment by d4rKn1ght** [comment] 2021-11-14 23:08
> Root cause might be that Chrome used within Station is outdated, see e.g. https://www.ecosia.org/search?q=whatsapp+qr+code+not+loading Station 2.0.9 seems to use Chrome 78.0, which dates back to 2019-10. See 'Help' > 'About Station'. Current version of Chrome would be 94.0, as of 2021-10. So my guess is that Chrome has to be updated...

- don't think that the version of Chrome is an issue. I am still using the older version of Station - 1.65.0 - and that too uses the older version of Chrome - 78, but the whatsapp-webb QR Code loads and lets me log in. 

![image](https://user-images.githubusercontent.com/18251085/141702365-663541a0-0bb3-4b26-aff6-fc6ef15591a7.png)

**Comment by bhishp** [comment] 2021-11-15 16:47
why did I decide to upgrade to the latest release 🤦🏽

**Comment by bhishp** [comment] 2021-11-15 16:51
> why did I decide to upgrade to the latest release 🤦🏽

I can confirm reverting to my old version works (also 1.65.0 but on MacOS BigSur 11.4)

<img width="548" alt="image" src="https://user-images.githubusercontent.com/12024258/141821496-77f3c930-127f-4dd9-a67a-6dd015678f01.png">

**Comment by A01378939** [comment] 2021-11-28 19:17
> > why did I decide to upgrade to the latest release 🤦🏽
> 
> I can confirm reverting to my old version works (also 1.65.0 but on MacOS BigSur 11.4)
> 
> <img alt="image" width="548" src="https://user-images.githubusercontent.com/12024258/141821496-77f3c930-127f-4dd9-a67a-6dd015678f01.png">

How can I revert to that old version??):

**Comment by abazeed** [comment] 2021-11-29 04:43
@A01378939, you can download it using this [**link**](https://mac.softpedia.com/dyn-postdownload.php/08d543919bc79a337e354da2c9fa2076/61a466a1/22e6e/4/1) for Mac.

**Comment by bhishp** [comment] 2021-11-29 09:58
> > > why did I decide to upgrade to the latest release 🤦🏽
> > 
> > 
> > I can confirm reverting to my old version works (also 1.65.0 but on MacOS BigSur 11.4)
> > <img alt="image" width="548" src="https://user-images.githubusercontent.com/12024258/141821496-77f3c930-127f-4dd9-a67a-6dd015678f01.png">
> 
> How can I revert to that old version??):

I deleted my app and managed to recover it from my trash can..

**Comment by A01378939** [comment] 2021-11-29 18:35
> @A01378939, you can download it using this [**link**](https://mac.softpedia.com/dyn-postdownload.php/08d543919bc79a337e354da2c9fa2076/61a466a1/22e6e/4/1) for Mac.

I have windows and the link does't load for me, maybe for the same fact that I'm on windows))):

**Comment by A01378939** [comment] 2021-11-29 18:35
> > > > why did I decide to upgrade to the latest release 🤦🏽
> > > 
> > > 
> > > I can confirm reverting to my old version works (also 1.65.0 but on MacOS BigSur 11.4)
> > > <img alt="image" width="548" src="https://user-images.githubusercontent.com/12024258/141821496-77f3c930-127f-4dd9-a67a-6dd015678f01.png">
> > 
> > 
> > How can I revert to that old version??):
> 
> I deleted my app and managed to recover it from my trash can..

Is there a way you could maybe upload the .exe file for me to install? 🥺

**Comment by haroldofurtado** [comment] 2022-07-18 13:04
Same problem here. I'm using Windows 11.

**Comment by jnvillar** [comment] 2022-11-24 19:09
This is still happening 😢 

Using the lastest beta version on mac os 13.0 

<img width="978" alt="Screenshot 2022-11-24 at 16 08 56" src="https://user-images.githubusercontent.com/7551569/203852100-9624a802-82d1-45e6-926d-13e276cb1d65.png">

**Comment by Seiifer** [comment] 2023-01-11 22:45
Yup same here, I guess Station is no longer maintained

**Closed** 2023-05-06 19:40 UTC
Labels: bug, outdated-electron
