### ISSUE TITLE
All Gmail tabs show same account

### ISSUE THREAD

**Issue by Hannah1577** [getstation/desktop-app#379] opened 2024-05-20 15:48 UTC
- Application version: 3.0.0
 - OS: Windows 11 Pro

I have 7 Gmail tabs on my Station and they're all for different accounts. When I first installed station, I set them all up and logged them in. However, every time Station force closes or crashes (which is often), upon reopening all the Gmail tabs show the same Gmail account inbox and there's no way for me to change it. Unless I create a whole new tab so I can log in again with the email account I want to see and then can't delete the old one. Any solutions to this?

Thanks

**Comment by viktor44** [comment] 2024-05-21 22:41
IMO crashing the application is not a common case.  
How many apps do you have in Station? Maybe it's too much for your computer's memory?
I tries to end application in Task Manager couple of times but Gmail sessions didn't lose.

As a quick recipe I would recommend to use `Reset Current Application` instead of recreate it.
In this case you only have to enter password one more time.

**Comment by viktor44** [comment] 2024-06-23 22:22
I'm closing it because can't see the way to reproduce it.

**Closed by viktor44** 2024-06-23 22:22 UTC
