### ISSUE TITLE
Can't connect Gmail

### ISSUE THREAD

**Issue by Bollaoros** [getstation/desktop-app#50] opened 2021-09-15 05:16 UTC
It gives me a client ID error when I try and integrate my Gmail

**Comment by Steve667** [comment] 2021-09-15 17:14
Having the same error, actually. 
```
Error 400: invalid_request
Missing required parameter: client_id
```
OS: macOS Big Sur 11.4

**Comment by LoKy-dev** [comment] 2021-09-16 08:48
Duplicae of #2

**Comment by LoKy-dev** [comment] 2021-09-16 08:48
Duplicate of #2

**Comment by BayAreaData** [comment] 2021-09-16 17:17
I third this. Gmail won't authorize, both Google accounts and Google-managed company accounts.

**Comment by apostolisgan7** [comment] 2021-09-17 08:40
Hey there! me too, i've got the same problem!

**Comment by lotusp** [comment] 2021-09-17 09:51
I got the same error:

Error 400： invalid_request
Missing required parameter: client_id

macOS Big Sur 11.4

**Comment by FiciencyAg** [comment] 2021-09-17 15:33
Same here

**Comment by davidbenucci** [comment] 2021-09-17 16:53
Me too

**Comment by SuperSonicSites** [comment] 2021-09-17 18:28
Same here

**Comment by raejbrown** [comment] 2021-09-20 15:33
I am having the same issue. Anything resolved yet?

Error 400: invalid_request
Missing required parameter: client_id

**Comment by Aynril** [comment] 2021-09-20 16:33
I have the same issue, any fixes available yet?

**Comment by wjani** [comment] 2021-09-21 05:13
Hello!
This is my problem too.
Is there a solution to your gmail account error?

**Comment by Techflow-ai** [comment] 2021-09-21 16:10
I have the issue too.

**Comment by Serubin** [comment] 2021-09-21 23:33
This needs to be solved by Station. They need to include their developer client id, I'm fairly certainly.

**Comment by Akansh0581** [comment] 2021-09-22 06:30
I have got the same issue
@getstation, please include the client Id as soon as possible
Otherwise the software would be useless

**Comment by robm87** [comment] 2021-09-22 10:05
Same problem here, I updated Station to newest version (lost all my old accounts :( ), now I want to configure all my accounts again. multiple problems; Gmail > invalid request, Whatsap > no QR code,

**Comment by quillevere** [comment] 2021-09-24 13:07
Same here. It's starting to become a real problem and not having a fix or even updates after 10 days is a bit frustrating...

**Comment by smallz207** [comment] 2021-09-24 16:46
SAME! It was working for me before... but now it's not and I'm getting the same error!

**Comment by convertl** [comment] 2021-09-27 12:43
Same problem here for a new Station installation on Windows

**Comment by Orbital101Studio** [comment] 2021-09-27 20:26
Same problem here. All google Apps dont work with business and personal accounts providing the same error message : 

Gmail auth error:
Error 400: invalid_request
Missing required parameter: client_id

**Comment by joeknouse** [comment] 2021-09-28 17:14
Yup. Same problem. Mac user.

**Comment by jkmgeo** [comment] 2021-09-28 17:48
Not tied to Station (or Adalo) in any way, but some quick searching after encountering the same problem suggests that this may be related to needing a Google developer client ID like mentioned in this link, especially steps 3 & 4: https://help.adalo.com/component-basics/marketplace-components/sign-in-with-google

I personally lack the know-how to update the Station app to rectify this, but maybe this points some dev in the right direction to get this issue fixed for all of us? @getstation 

Pinging issues #2 #28 #29 #32 #40 #59 #60, as well.

**Comment by ameliasellsmaine** [comment] 2021-10-05 16:37
curious if we are ever going to get a fix for this....

**Comment by GitToby** [comment] 2021-10-11 08:27
looks like #70 and #68 too now

**Comment by viktor44** [comment] 2023-05-07 12:16
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)

**Closed by viktor44** 2023-05-07 12:16 UTC
