### ISSUE TITLE
App not secure

### ISSUE THREAD

**Issue by AE102** [getstation/desktop-app#17] opened 2021-07-19 14:09 UTC
Hi,
This is my first using station when I try to sign in to Gmail, google chat or drive I get an error that says: This browser or app may not be secure. or Error 400: invalid_request. 
![Screenshot 2021-07-19 150851](https://user-images.githubusercontent.com/71657811/126173368-4f6d7525-67cb-405c-91ba-e414f8db1bcc.jpg)
![Screenshot 2021-07-19 150909](https://user-images.githubusercontent.com/71657811/126173417-724278c9-383b-4dd0-ae7a-4a899194feb8.jpg)

**Comment by chetan** [comment] 2021-07-19 15:26
Duplicate of #2

**Comment by AE102** [comment] 2021-07-19 16:59
> Duplicate of #2

I an using windows 10 not  macos

**Comment by magne4000** [comment] 2021-07-19 21:31
Closed in favor of #2

**Closed by magne4000** 2021-07-19 21:31 UTC
Labels: duplicate
