### ISSUE TITLE
Cant login in Gmail or any other google service "ERROR_400 bad request"

### ISSUE THREAD

**Issue by ahsanfarooq210** [getstation/desktop-app#19] opened 2021-07-20 19:17 UTC
when i click "Add a new account" it takes me to the browser. i put my email and password and i am constantly getting this error
"ERROR_400 bad request" image attached below
![Screenshot 2021-07-21 001650](https://user-images.githubusercontent.com/61400176/126382638-487c42de-496e-40ee-9a63-42174337fe59.png)

**Comment by void** [comment] 2021-07-20 22:18
same here

**Comment by patrickphoto** [comment] 2021-07-21 03:16
Yeah, nothing from Google works, seems to be an Oath implementation issue with the Open Source version?

**Comment by krunk4ever** [comment] 2021-07-21 09:34
Came to post the same issue.

**Comment by krunk4ever** [comment] 2021-07-21 17:02
If you're looking for the previous version (will be stop working on 8/31) you can download version 1.65 here:
https://www.macupdate.com/app/mac/60202/station
https://mac.softpedia.com/get/Internet-Utilities/getStation.shtml

**Comment by Hobadee** [comment] 2021-07-21 18:47
This is a duplicate of #2

**Comment by anuzk13** [comment] 2021-07-22 16:16
same error

**Comment by magne4000** [comment] 2021-07-22 21:36
Duplicate of #2

**Closed by magne4000** 2021-07-22 21:36 UTC
Labels: bug, duplicate
